grpc_port: "50051"
database_type: postgres
log_level: info
database_host: postgres
database_port: "5432"
database_username: postgres
database_password: password
database_name: postgres_db
database_ssl_mode: disable
database_schema: public
database_max_open_conns: 25
database_max_conn_idle_time: 5m
database_max_conn_lifetime: 30m
database_health_check_period: 1m
